title: Hello, world! I'm Gurnoor Singh
description: > # this means to ignore newlines until "baseurl:"
  AI & Deep Learning Enthusiast | Linux Lover
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: noor30196 #if your site has a twitter account, enter it here

# Author Settings
author: Gurnoor Singh # add your name
author-img: GURNOOR.jpg # add your photo
about-author: An autodidactic Ambivert | AI & Deep Learning Enthusiast | Linux Lover # add description
social-twitter: noor30196 # add your Twitter handle
social-facebook: gurnoor.singh.7731 # add your Facebook handle 
social-github: imgurnoor # add your Github handle
social-linkedin: /gurnoor-singh-699a6397/ # add your Linkedin handle
social-email: gurnoor30196@gmail.com # add your Email address
 

# Disqus
discus-identifier: GURNOOR SINGH # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
